#命令前缀
Prefix: '&aLite&eAnnouncer &f&l>>> '

#插件语言设置（默认提供简体中文与英文的语言文件）
Language: Chinese

Permissions:
    #命令相关权限
    Commands:
        Help: 
            Permission: liteannouncer.command.help
            #是否默认拥有权限
            Default: true
        Reload: 
            Permission: liteannouncer.command.reload
            Default: false
        View: 
            Permission: liteannouncer.command.view
            Default: false
        List: 
            Permission: liteannouncer.command.list
            Default: false